version: "3.8"

services:
  auto-yt-dlp:
    build: .
    container_name: auto-yt-dlp
    restart: unless-stopped
    environment:
      - TZ=Europe/Lisbon
      - CRON_SCHEDULE=0 * * * * # Every hour (default)
    volumes:
      - ./config.yaml:/app/config/config.yaml # Configuration file
      - ./archives:/app/archives # Directory for archives
      - ./downloads:/app/downloads # Directory for output files
